In [10]:
import numpy as np

1. Ստեղծել np զանգված, որը կպարունակի 100 պատահական ամբողջ թիվ։ Այնուհետև ստանալ այն տարրերի ինդեքսները, որոնք ավարտվում են 6-ով։

In [11]:
arr = np.random.randint(0, 100, 100)
arr

array([30, 52, 22, 60, 86, 20, 97, 29, 63, 45, 21, 87, 52, 41,  6, 28,  3,
        5, 34, 78, 45, 54, 67, 32, 18, 25, 61, 72, 56, 10, 77, 85, 15, 87,
       89, 96, 37,  6, 59, 40, 75, 70, 64, 97, 43, 87, 47, 77, 17,  6, 69,
       39, 30, 10, 79, 68, 71, 74, 52, 21, 86, 13, 48, 29, 54, 83, 96, 74,
       78, 53, 83, 46, 26, 40, 20, 31,  8, 22, 33, 92, 68, 13, 66, 98,  5,
       84, 50, 97,  0, 63, 81, 26, 98, 41, 53, 87, 77, 58, 65,  8])

In [15]:
arr[np.where(arr % 10 == 6)]

array([86,  6, 56, 96,  6,  6, 86, 96, 46, 26, 66, 26])

In [18]:
arr[arr % 10 == 6]

array([86,  6, 56, 96,  6,  6, 86, 96, 46, 26, 66, 26])

2. Ստեղծել np զանգված, որի բոլոր տարրերը կլինեն 0-ներ, իսկ անկյունագծայինները՝ 1։

In [25]:
n = 10
arr = np.zeros((n, n))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.fill_diagonal(arr, 1)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
i = 0
for i in range(n):
    arr[n - i - 1][i] = 1

arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

3. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից (հիշեցում․ asarray, array)։ Ապա կցեք երկու զանգվածներն իրար հորիզոնական ուղությամբ։ 

օրինակ, եթե
```python
import numpy as np

arr_1 -> array([1, 2, 3])
arr_2 -> array([4, 5, 6])

```
ապա արդյունքը պետք է լինի
```python
array([1, 2, 3, 4, 5, 6])
```

In [35]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

4. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից (հիշեցում․ asarray, array)։ Ապա կցեք երկու զանգվածներն իրար վերտիկալ ուղությամբ։ 

օրինակ, եթե
```python
import numpy as np

arr_1 -> array([1, 2, 3])
arr_2 -> array([4, 5, 6])

```
ապա արդյունքը պետք է լինի
```python
array([[1, 2, 3],
       [4, 5, 6]])
```

In [32]:
np.vstack((arr_1, arr_2))

array([[1, 2, 3],
       [4, 5, 6]])

5. Ստեղծել երկչափ զանգված, որը կունենա (3, 3) shape: Այնուհետև ստեղծել նոր զանգված, որը կլինի նախորդ զանգվածը, սակայն առաջին և երրորդ սյուների տեղերը փոխած։

In [36]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr_2 = arr[[0, 2, 1], :]
arr_2

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

6.  Ստեղծել երեք զանգված։ Առաջինը պետք է պարունակի միայն 0-ներ, երկրորդը միայն 1-եր, իսկ երրորդը միայն 9-եր։

In [58]:
n = 5
arr_0 = np.zeros(shape=(n, n))
arr_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
arr_1 = np.ones(shape=(n, n))
arr_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
arr_9 = np.zeros(shape=(n, n))
arr_9.fill(9)
arr_9

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

7. Ստեղծել (10, 10) shape-ով զանգված։ Ապա փոխել դրա shape-ը հնարավոր բոլոր տարբերակներով։ 

In [65]:
arr = np.arange(0, 100).reshape(10, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
arr.reshape(100, 1, 1, 1, 1)

array([[[[[ 0]]]],



       [[[[ 1]]]],



       [[[[ 2]]]],



       [[[[ 3]]]],



       [[[[ 4]]]],



       [[[[ 5]]]],



       [[[[ 6]]]],



       [[[[ 7]]]],



       [[[[ 8]]]],



       [[[[ 9]]]],



       [[[[10]]]],



       [[[[11]]]],



       [[[[12]]]],



       [[[[13]]]],



       [[[[14]]]],



       [[[[15]]]],



       [[[[16]]]],



       [[[[17]]]],



       [[[[18]]]],



       [[[[19]]]],



       [[[[20]]]],



       [[[[21]]]],



       [[[[22]]]],



       [[[[23]]]],



       [[[[24]]]],



       [[[[25]]]],



       [[[[26]]]],



       [[[[27]]]],



       [[[[28]]]],



       [[[[29]]]],



       [[[[30]]]],



       [[[[31]]]],



       [[[[32]]]],



       [[[[33]]]],



       [[[[34]]]],



       [[[[35]]]],



       [[[[36]]]],



       [[[[37]]]],



       [[[[38]]]],



       [[[[39]]]],



       [[[[40]]]],



       [[[[41]]]],



       [[[[42]]]],



       [[[[43]]]],



       [[[[44]]]],



       [[[

8. Ստեղծել երկու երկչափ զանգված և հաշվել դրանց ա) տարր առ տարր արտադրյալը, բ) մատրիցային արտադրյալը։

In [91]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(11, 20).reshape(3, 3)
np.multiply(a, b)  # a * b
a * b

np.dot(a, b)  # a @ b
a @ b

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])


9. Ստեղծել երկու զանգված (10, 10) shape-ի, որոնք կպարունակեն 0-ից 20-ը պատահական թվեր։ Բաժանել մատրիցներն իրար։ Այնուհետև առանձնացնել նոր մատրիցի մեջ մատրիցների այն տարրերը, որոնք թիվ են (inf կամ nan չեն): Ստանալ inf-երի և nan-երի նաև դրանց ինդեքսները։

In [98]:
arr_1 = np.random.randint(0, 20, 100).reshape(10, 10)
print(arr_1)

arr_2 = np.random.randint(0, 20, 100).reshape(10, 10)
arr_2

[[10 10  3  0  6 15 17 15 13  8]
 [ 5 15  3 14 18 13  3  6 12 12]
 [10 15 15  9 12 16 14  9  6 14]
 [17  1 16  8  2  0  7 19  2 18]
 [ 9 14 12 11  7  1 18  5 19  4]
 [16  0 10  5  5  6 18 11 16 13]
 [ 2 19  9  7 14  2  6 10 14 11]
 [ 4  9 12  1 11 18  1 18  4  0]
 [ 7 13  7  3 12  5  5  4 10  4]
 [ 3 18  7 12 14 12 16  3  1 15]]


array([[14,  1, 10, 15, 12, 13, 13, 18,  6, 17],
       [16,  6, 11, 14,  7, 13, 19,  7,  5, 10],
       [12,  3,  0,  7, 15,  1, 18,  0, 16, 11],
       [ 3, 17, 10,  8,  6, 19,  7, 17,  3, 15],
       [16, 11,  1,  6,  2,  6,  7,  5, 16,  3],
       [15, 19, 15, 17,  6, 13, 12, 19,  9, 10],
       [ 7,  6, 16, 11,  7,  0,  2,  6,  4,  8],
       [ 2,  0,  6, 17,  1, 13, 17,  6, 13,  7],
       [13, 12,  4,  5, 16,  6,  6,  3,  6,  0],
       [10,  9,  7,  3,  8, 18,  4,  8, 11,  1]])

In [117]:
div = arr_1 / arr_2

print(div)

div[np.where((div != np.inf) & (div != np.nan))]

[[ 0.71428571 10.          0.3         0.          0.5         1.15384615
   1.30769231  0.83333333  2.16666667  0.47058824]
 [ 0.3125      2.5         0.27272727  1.          2.57142857  1.
   0.15789474  0.85714286  2.4         1.2       ]
 [ 0.83333333  5.                 inf  1.28571429  0.8        16.
   0.77777778         inf  0.375       1.27272727]
 [ 5.66666667  0.05882353  1.6         1.          0.33333333  0.
   1.          1.11764706  0.66666667  1.2       ]
 [ 0.5625      1.27272727 12.          1.83333333  3.5         0.16666667
   2.57142857  1.          1.1875      1.33333333]
 [ 1.06666667  0.          0.66666667  0.29411765  0.83333333  0.46153846
   1.5         0.57894737  1.77777778  1.3       ]
 [ 0.28571429  3.16666667  0.5625      0.63636364  2.                 inf
   3.          1.66666667  3.5         1.375     ]
 [ 2.                 inf  2.          0.05882353 11.          1.38461538
   0.05882353  3.          0.30769231  0.        ]
 [ 0.53846154  1.0833333

<ipython-input-117-33441779203c>:1: RuntimeWarning: divide by zero encountered in true_divide
  div = arr_1 / arr_2


array([ 0.71428571, 10.        ,  0.3       ,  0.        ,  0.5       ,
        1.15384615,  1.30769231,  0.83333333,  2.16666667,  0.47058824,
        0.3125    ,  2.5       ,  0.27272727,  1.        ,  2.57142857,
        1.        ,  0.15789474,  0.85714286,  2.4       ,  1.2       ,
        0.83333333,  5.        ,  1.28571429,  0.8       , 16.        ,
        0.77777778,  0.375     ,  1.27272727,  5.66666667,  0.05882353,
        1.6       ,  1.        ,  0.33333333,  0.        ,  1.        ,
        1.11764706,  0.66666667,  1.2       ,  0.5625    ,  1.27272727,
       12.        ,  1.83333333,  3.5       ,  0.16666667,  2.57142857,
        1.        ,  1.1875    ,  1.33333333,  1.06666667,  0.        ,
        0.66666667,  0.29411765,  0.83333333,  0.46153846,  1.5       ,
        0.57894737,  1.77777778,  1.3       ,  0.28571429,  3.16666667,
        0.5625    ,  0.63636364,  2.        ,  3.        ,  1.66666667,
        3.5       ,  1.375     ,  2.        ,  2.        ,  0.05

10. Ստեղծել (3, 3) մատրից, որի տարրերը կլինեն 11-19, սակայն բացահայտ կերպով սահմանել տարրերի տիպը որպես float։

In [121]:
np.arange(11, 20, dtype=float).reshape(3, 3).T

array([[11., 14., 17.],
       [12., 15., 18.],
       [13., 16., 19.]])

In [122]:
arr = np.random.randint(0, 100, 100).reshape(10, 10)
arr

array([[24, 88, 88, 26, 24, 61, 55, 34, 21, 54],
       [52, 99, 58, 16, 83, 42,  2, 77,  6,  7],
       [81, 56, 50, 90,  5, 39, 79, 68, 64, 56],
       [30, 37, 97, 73, 73, 96, 23, 24, 59, 39],
       [42, 14, 82, 43, 59, 91, 30, 95, 97, 62],
       [41, 72,  4, 31, 87, 38, 79, 17, 31, 23],
       [ 2, 90, 94, 84,  4, 38, 78, 83, 22, 24],
       [17, 40, 15, 99, 42, 60, 73, 69, 93, 34],
       [56, 17, 25,  6,  9,  3, 54, 77, 77,  7],
       [ 3, 78,  5, 61, 61, 19, 25, 59,  3, 94]])

In [129]:
np.mean(arr, axis=0)

array([34.8, 59.1, 51.8, 52.9, 44.7, 48.7, 49.8, 60.3, 47.3, 40. ])

In [ ]:
arr[5, 4 ,3 ,2 ,1 ,0]